language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: pages:git
  edge: true # opt into v2 beta
  local_dir: build
  token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  target_branch: master
  on:
    branch: source
  keep_history: true # Keep history of commits
  verbose: true
  commit_message: "TravisCI Deploy: ${TRAVIS_COMMIT}" # In v2